spring.application.name=DA_Erronka2
spring.datasource.url=jdbc:mysql://localhost:3306/E2
spring.datasource.username=root
spring.datasource.password=algomuysencillo
spring.mvc.static-path-pattern=/static/**
logging.level.org.springframework.web=DEBUG
logging.level.eus.fpsanturtzilh=DEBUG
logging.level.root=INFO
spring.web.resources.add-mappings=false


# Mostrar logs de nivel ERROR y superior en la consola
logging.level.org.springframework=ERROR
